### PR TITLE
Adds safari web view controller page for testing

### PR DESCRIPTION
**Pull request by jescriba**

### CODE REVIEW

**Comment by jescriba** [comment]
@jmoody I added a tab for Safari controller, and I tried writing tests for it - but I don't think calabash can currently query inside of the safari controller? 

Output from tree:
```
calabash-ios 0.20.0> tree
[UIWindow]
  [UILayoutContainerView]
    [UITransitionView]
      [UIViewControllerWrapperView]
        [UIView] [id:landing page] [label:Zielseite]
          [_UISizeTrackingView]
            [_UIRemoteView] [id:RemoteViewBridge]
          [UIView]
    [UITabBar]
      [_UIBarBackground]
        [UIImageView]
      [UITabBarButton] [label:UIWebView]
        [UITabBarSwappableImageView] [id:UIWebViewTab]
        [UITabBarButtonLabel] [label:UIWebView] [text:UIWebView]
      [UITabBarButton] [label:WKWebView]
        [UITabBarSwappableImageView] [id:WKWebViewTab]
        [UITabBarButtonLabel] [label:WKWebView] [text:WKWebView]
      [UITabBarButton] [label:SafariController]
        [UITabBarButtonLabel] [label:SafariController] [text:SafariController]
```

I tried `query("view:'UIRemoteView' css:'*'")` to no avail as well as a few other similar queries (descendants of main UIView on safari page)

**Comment by jmoody** [comment]
> LPServer query

Correct.  The LPServer cannot detect elements inside the Safari View Controller.  The question is, can DeviceAgent (in its current implementation) interact with these elements or do we need to update DeviceAgent?

**Comment by jescriba** [comment]
@jmoody Not entirely sure the best approach to testing DeviceAgent interaction but I was able to do a basic `touch("*")` and saw the webview on the Safari View Controller respond to the event when I had initially centered a textfield for instance. So looks like interactions work at least - is there something else I can do to test in this case?

**Comment by jmoody** [comment]
This should be rebased against master and force pushed.

**Pull request merged**
